
package es.um.swit.backup.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.6
 * Tue Aug 28 20:17:49 CEST 2018
 * Generated source version: 3.2.6
 */

@XmlRootElement(name = "borrarRegistro", namespace = "http://service.backup.swit.um.es/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "borrarRegistro", namespace = "http://service.backup.swit.um.es/")

public class BorrarRegistro {

    @XmlElement(name = "idRegistro")
    private java.lang.String idRegistro;

    public java.lang.String getIdRegistro() {
        return this.idRegistro;
    }

    public void setIdRegistro(java.lang.String newIdRegistro)  {
        this.idRegistro = newIdRegistro;
    }

}

