
package es.um.swit.backup.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.6
 * Tue Aug 28 20:17:49 CEST 2018
 * Generated source version: 3.2.6
 */

@XmlRootElement(name = "recuperarTodosRegistrosResponse", namespace = "http://service.backup.swit.um.es/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "recuperarTodosRegistrosResponse", namespace = "http://service.backup.swit.um.es/")

public class RecuperarTodosRegistrosResponse {

    @XmlElement(name = "listaRegistros")
    private java.util.List<es.um.swit.backup.beans.Registro> listaRegistros;

    public java.util.List<es.um.swit.backup.beans.Registro> getListaRegistros() {
        return this.listaRegistros;
    }

    public void setListaRegistros(java.util.List<es.um.swit.backup.beans.Registro> newListaRegistros)  {
        this.listaRegistros = newListaRegistros;
    }

}

