
package es.um.swit.backup.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.6
 * Sun Aug 26 20:48:02 CEST 2018
 * Generated source version: 3.2.6
 */

@XmlRootElement(name = "recuperarMappingsResponse", namespace = "http://service.backup.swit.um.es/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "recuperarMappingsResponse", namespace = "http://service.backup.swit.um.es/")

public class RecuperarMappingsResponse {

    @XmlElement(name = "respuestaRecuperarRegistros")
    private es.um.swit.backup.beans.RespuestaRecuperarRegistro respuestaRecuperarRegistros;

    public es.um.swit.backup.beans.RespuestaRecuperarRegistro getRespuestaRecuperarRegistros() {
        return this.respuestaRecuperarRegistros;
    }

    public void setRespuestaRecuperarRegistros(es.um.swit.backup.beans.RespuestaRecuperarRegistro newRespuestaRecuperarRegistros)  {
        this.respuestaRecuperarRegistros = newRespuestaRecuperarRegistros;
    }

}

