
package es.um.swit.backup.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.6
 * Sun Aug 26 20:48:02 CEST 2018
 * Generated source version: 3.2.6
 */

@XmlRootElement(name = "reemplazarMappings", namespace = "http://service.backup.swit.um.es/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reemplazarMappings", namespace = "http://service.backup.swit.um.es/", propOrder = {"mappingsFile", "idRegistro"})

public class ReemplazarMappings {

    @XmlElement(name = "mappingsFile")
    private byte[] mappingsFile;
    @XmlElement(name = "idRegistro")
    private java.lang.String idRegistro;

    public byte[] getMappingsFile() {
        return this.mappingsFile;
    }

    public void setMappingsFile(byte[] newMappingsFile)  {
        this.mappingsFile = newMappingsFile;
    }

    public java.lang.String getIdRegistro() {
        return this.idRegistro;
    }

    public void setIdRegistro(java.lang.String newIdRegistro)  {
        this.idRegistro = newIdRegistro;
    }

}

