package es.um.swit.backup.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-08-29T19:16:15.847+02:00
 * Generated source version: 3.2.6
 *
 */
@WebServiceClient(name = "GestorRegistrosService",
                  wsdlLocation = "http://localhost:8081/BackupWebService/services/GestorRegistros?wsdl",
                  targetNamespace = "http://service.backup.swit.um.es/")
public class GestorRegistrosService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.backup.swit.um.es/", "GestorRegistrosService");
    public final static QName GestorRegistrosPort = new QName("http://service.backup.swit.um.es/", "GestorRegistrosPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8081/BackupWebService/services/GestorRegistros?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GestorRegistrosService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8081/BackupWebService/services/GestorRegistros?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GestorRegistrosService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GestorRegistrosService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GestorRegistrosService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public GestorRegistrosService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public GestorRegistrosService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public GestorRegistrosService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns GestorRegistros
     */
    @WebEndpoint(name = "GestorRegistrosPort")
    public GestorRegistros getGestorRegistrosPort() {
        return super.getPort(GestorRegistrosPort, GestorRegistros.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GestorRegistros
     */
    @WebEndpoint(name = "GestorRegistrosPort")
    public GestorRegistros getGestorRegistrosPort(WebServiceFeature... features) {
        return super.getPort(GestorRegistrosPort, GestorRegistros.class, features);
    }

}
